export const DEFAULT_RISKS = [
  { id: 1, area: "Revenue Recognition", description: "Risk of material misstatement due to fraud in revenue recognition per ISA 240", inherentLikelihood: 4, inherentImpact: 5, controls: "Segregation of duties, automated invoice matching, monthly analytical review", controlEffectiveness: 3, residualLikelihood: 2, residualImpact: 4, response: "Extended substantive testing, cut-off testing, journal entry analysis" },
  { id: 2, area: "Management Override", description: "Risk of management override of controls per ISA 240 — presumed risk", inherentLikelihood: 3, inherentImpact: 5, controls: "Board oversight, independent audit committee, whistleblower policy", controlEffectiveness: 2, residualLikelihood: 2, residualImpact: 4, response: "Journal entry testing, review of estimates, evaluate business rationale of significant transactions" },
  { id: 3, area: "Going Concern", description: "Risk that entity may not continue as a going concern per ISA 570", inherentLikelihood: 2, inherentImpact: 5, controls: "Cash flow monitoring, covenant tracking, board review of forecasts", controlEffectiveness: 3, residualLikelihood: 1, residualImpact: 5, response: "Review cash flow forecasts, assess loan covenants, evaluate subsequent events" },
];

export const DEFAULT_FINDINGS = [
  { id: 1, ref: "F-001", title: "Lack of segregation of duties in cash receipting", component: "Cash & Bank", severity: "high", condition: "One individual is responsible for receiving, recording, and depositing cash receipts without independent review.", criteria: "ISA 315 — Effective internal controls require adequate segregation of duties to prevent and detect errors or fraud.", cause: "Small finance team with limited staff capacity.", effect: "Increased risk of misappropriation of cash receipts going undetected.", recommendation: "Assign cash receipt recording to a different staff member than the person handling physical cash. Implement daily supervisory review of cash receipts journal.", managementResponse: "", targetDate: "", status: "open" },
  { id: 2, ref: "F-002", title: "Revenue cut-off error identified", component: "Revenue & Income", severity: "medium", condition: "Three sales invoices totaling R245,000 dated in January were recorded in the December general ledger.", criteria: "IFRS 15 — Revenue should be recognised when control passes to the customer. IAS 1 requires proper period allocation.", cause: "Month-end close procedures do not include a formal cut-off review checklist.", effect: "Revenue overstated by R245,000 at year-end (below materiality but noted for management attention).", recommendation: "Implement a formal month-end cut-off checklist that requires matching of delivery notes to invoice dates. Review all invoices within 5 days of year-end.", managementResponse: "", targetDate: "", status: "open" },
];
